import '../repository/cart_repository.dart';
import '../repository/product_repository.dart';
import '../models/cart_item.dart';
import '../models/product.dart';
import 'dependency_injection.dart';
import 'auth_service.dart';

class CartService {
  final CartRepository _cartRepository = getIt<CartRepository>();
  final ProductRepository _productRepository = getIt<ProductRepository>();
  final AuthService _authService = AuthService();

  // Get current user cart items
  Future<List<CartItem>> getCurrentUserCartItems() async {
    try {
      if (!_authService.isAuthenticated) {
        throw Exception('User not authenticated');
      }

      final userId = _authService.currentUser!.id;
      return await _cartRepository.getUserCartItems(userId);
    } catch (e) {
      throw Exception('Failed to fetch cart items: $e');
    }
  }

  // Add item to cart
  Future<CartItem> addToCart({
    required String productId,
    int quantity = 1,
  }) async {
    try {
      if (!_authService.isAuthenticated) {
        throw Exception('User not authenticated');
      }

      if (quantity <= 0) {
        throw Exception('Quantity must be greater than 0');
      }

      // Verify product exists and is available
      final product = await _productRepository.getProductById(productId);
      if (product == null) {
        throw Exception('Product not found');
      }

      if (!product.isAvailable) {
        throw Exception('Product is not available');
      }

      final userId = _authService.currentUser!.id;
      final cartItem = CartItem(
        id: '', // Will be generated by Supabase
        userId: userId,
        productId: productId,
        quantity: quantity,
      );

      return await _cartRepository.addToCart(cartItem);
    } catch (e) {
      throw Exception('Failed to add item to cart: $e');
    }
  }

  // Update cart item quantity
  Future<CartItem> updateQuantity(String cartItemId, int quantity) async {
    try {
      if (quantity <= 0) {
        await removeFromCart(cartItemId);
        throw Exception('Item removed from cart');
      }

      return await _cartRepository.updateQuantity(cartItemId, quantity);
    } catch (e) {
      throw Exception('Failed to update quantity: $e');
    }
  }

  // Remove item from cart
  Future<void> removeFromCart(String cartItemId) async {
    try {
      await _cartRepository.removeFromCart(cartItemId);
    } catch (e) {
      throw Exception('Failed to remove item from cart: $e');
    }
  }

  // Clear entire cart
  Future<void> clearCart() async {
    try {
      if (!_authService.isAuthenticated) {
        throw Exception('User not authenticated');
      }

      final userId = _authService.currentUser!.id;
      await _cartRepository.clearUserCart(userId);
    } catch (e) {
      throw Exception('Failed to clear cart: $e');
    }
  }

  // Get cart items with product details
  Future<List<CartItemWithProduct>> getCartItemsWithProducts() async {
    try {
      final cartItems = await getCurrentUserCartItems();
      final List<CartItemWithProduct> result = [];

      for (final cartItem in cartItems) {
        final product =
            await _productRepository.getProductById(cartItem.productId);
        result.add(CartItemWithProduct(
          cartItem: cartItem,
          product: product,
        ));
      }

      return result;
    } catch (e) {
      throw Exception('Failed to fetch cart items with products: $e');
    }
  }

  // Get cart total amount
  Future<double> getCartTotal() async {
    try {
      final cartItemsWithProducts = await getCartItemsWithProducts();

      double total = 0;
      for (final item in cartItemsWithProducts) {
        if (item.product != null) {
          total += item.product!.price * item.cartItem.quantity;
        }
      }

      return total;
    } catch (e) {
      throw Exception('Failed to calculate cart total: $e');
    }
  }

  // Get cart items count
  Future<int> getCartItemsCount() async {
    try {
      if (!_authService.isAuthenticated) {
        return 0;
      }

      final userId = _authService.currentUser!.id;
      return await _cartRepository.getUserCartItemsCount(userId);
    } catch (e) {
      throw Exception('Failed to get cart items count: $e');
    }
  }

  // Check if product is in cart
  Future<CartItem?> getCartItemForProduct(String productId) async {
    try {
      if (!_authService.isAuthenticated) {
        return null;
      }

      final userId = _authService.currentUser!.id;
      return await _cartRepository.getCartItemByUserAndProduct(
          userId, productId);
    } catch (e) {
      throw Exception('Failed to check cart item: $e');
    }
  }

  // Validate cart before checkout
  Future<CartValidationResult> validateCart() async {
    try {
      final cartItemsWithProducts = await getCartItemsWithProducts();
      final List<String> errors = [];
      final List<CartItemWithProduct> validItems = [];

      for (final item in cartItemsWithProducts) {
        if (item.product == null) {
          errors.add('Product ${item.cartItem.productId} not found');
          continue;
        }

        if (!item.product!.isAvailable) {
          errors.add('${item.product!.name} is no longer available');
          continue;
        }

        validItems.add(item);
      }

      return CartValidationResult(
        isValid: errors.isEmpty,
        errors: errors,
        validItems: validItems,
      );
    } catch (e) {
      throw Exception('Failed to validate cart: $e');
    }
  }
}

// Helper classes
class CartItemWithProduct {
  final CartItem cartItem;
  final Product? product;

  CartItemWithProduct({
    required this.cartItem,
    this.product,
  });
}

class CartValidationResult {
  final bool isValid;
  final List<String> errors;
  final List<CartItemWithProduct> validItems;

  CartValidationResult({
    required this.isValid,
    required this.errors,
    required this.validItems,
  });
}
