import '../repository/order_repository.dart';
import '../repository/order_item_repository.dart';
import '../models/order.dart';
import '../models/order_item.dart';
import 'dependency_injection.dart';
import 'auth_service.dart';
import 'cart_service.dart';

class OrderService {
  final OrderRepository _orderRepository = getIt<OrderRepository>();
  final OrderItemRepository _orderItemRepository = getIt<OrderItemRepository>();
  final AuthService _authService = AuthService();
  final CartService _cartService = CartService();

  // Get current user orders
  Future<List<Order>> getCurrentUserOrders() async {
    try {
      if (!_authService.isAuthenticated) {
        throw Exception('User not authenticated');
      }

      final userId = _authService.currentUser!.id;
      return await _orderRepository.getUserOrders(userId);
    } catch (e) {
      throw Exception('Failed to fetch user orders: $e');
    }
  }

  // Get order by ID
  Future<Order?> getOrderById(String orderId) async {
    try {
      return await _orderRepository.getOrderById(orderId);
    } catch (e) {
      throw Exception('Failed to fetch order: $e');
    }
  }

  // Get order with items
  Future<Order?> getOrderWithItems(String orderId) async {
    try {
      return await _orderRepository.getOrderWithItems(orderId);
    } catch (e) {
      throw Exception('Failed to fetch order with items: $e');
    }
  }

  // Create order from cart
  Future<Order> createOrderFromCart() async {
    try {
      if (!_authService.isAuthenticated) {
        throw Exception('User not authenticated');
      }

      // Validate cart first
      final cartValidation = await _cartService.validateCart();
      if (!cartValidation.isValid) {
        throw Exception(
            'Cart validation failed: ${cartValidation.errors.join(', ')}');
      }

      if (cartValidation.validItems.isEmpty) {
        throw Exception('Cart is empty');
      }

      final userId = _authService.currentUser!.id;
      final totalPrice = cartValidation.validItems.fold<double>(
        0,
        (sum, item) => sum + (item.product!.price * item.cartItem.quantity),
      );

      // Create order
      final order = Order(
        id: '', // Will be generated by Supabase
        userId: userId,
        totalPrice: totalPrice,
        createdAt: DateTime.now(),
        status: OrderStatus.pending,
      );

      final createdOrder = await _orderRepository.createOrder(order);

      // Create order items
      final orderItems = cartValidation.validItems
          .map((item) => OrderItem(
                id: '', // Will be generated by Supabase
                orderId: createdOrder.id,
                productId: item.cartItem.productId,
                quantity: item.cartItem.quantity,
                price: item.product!.price, // Save price at time of order
              ))
          .toList();

      await _orderItemRepository.createOrderItems(orderItems);

      // Clear cart after successful order creation
      await _cartService.clearCart();

      return createdOrder;
    } catch (e) {
      throw Exception('Failed to create order: $e');
    }
  }

  // Update order status
  Future<Order> updateOrderStatus(String orderId, OrderStatus status) async {
    try {
      return await _orderRepository.updateOrderStatus(orderId, status);
    } catch (e) {
      throw Exception('Failed to update order status: $e');
    }
  }

  // Cancel order
  Future<Order> cancelOrder(String orderId) async {
    try {
      final order = await getOrderById(orderId);
      if (order == null) {
        throw Exception('Order not found');
      }

      if (order.status != OrderStatus.pending) {
        throw Exception('Can only cancel pending orders');
      }

      return await updateOrderStatus(orderId, OrderStatus.cancelled);
    } catch (e) {
      throw Exception('Failed to cancel order: $e');
    }
  }

  // Get user orders by status
  Future<List<Order>> getUserOrdersByStatus(OrderStatus status) async {
    try {
      if (!_authService.isAuthenticated) {
        throw Exception('User not authenticated');
      }

      final userId = _authService.currentUser!.id;
      return await _orderRepository.getUserOrdersByStatus(userId, status);
    } catch (e) {
      throw Exception('Failed to fetch orders by status: $e');
    }
  }

  // Get order items for specific order
  Future<List<OrderItem>> getOrderItems(String orderId) async {
    try {
      return await _orderItemRepository.getOrderItems(orderId);
    } catch (e) {
      throw Exception('Failed to fetch order items: $e');
    }
  }

  // Get order items with product details
  Future<List<Map<String, dynamic>>> getOrderItemsWithProducts(
      String orderId) async {
    try {
      return await _orderItemRepository.getOrderItemsWithProducts(orderId);
    } catch (e) {
      throw Exception('Failed to fetch order items with products: $e');
    }
  }

  // Get order summary
  Future<OrderSummary> getOrderSummary(String orderId) async {
    try {
      final order = await getOrderById(orderId);
      if (order == null) {
        throw Exception('Order not found');
      }

      final orderItems = await getOrderItems(orderId);
      final itemCount =
          orderItems.fold<int>(0, (sum, item) => sum + item.quantity);

      return OrderSummary(
        order: order,
        itemCount: itemCount,
        orderItems: orderItems,
      );
    } catch (e) {
      throw Exception('Failed to get order summary: $e');
    }
  }

  // Get user order statistics
  Future<UserOrderStats> getUserOrderStats() async {
    try {
      if (!_authService.isAuthenticated) {
        throw Exception('User not authenticated');
      }

      final orders = await getCurrentUserOrders();

      final totalOrders = orders.length;
      final totalSpent =
          orders.fold<double>(0, (sum, order) => sum + order.totalPrice);

      final statusCounts = <OrderStatus, int>{};
      for (final status in OrderStatus.values) {
        statusCounts[status] =
            orders.where((order) => order.status == status).length;
      }

      return UserOrderStats(
        totalOrders: totalOrders,
        totalSpent: totalSpent,
        statusCounts: statusCounts,
        recentOrders: orders.take(5).toList(),
      );
    } catch (e) {
      throw Exception('Failed to get user order stats: $e');
    }
  }
}

// Helper classes
class OrderSummary {
  final Order order;
  final int itemCount;
  final List<OrderItem> orderItems;

  OrderSummary({
    required this.order,
    required this.itemCount,
    required this.orderItems,
  });
}

class UserOrderStats {
  final int totalOrders;
  final double totalSpent;
  final Map<OrderStatus, int> statusCounts;
  final List<Order> recentOrders;

  UserOrderStats({
    required this.totalOrders,
    required this.totalSpent,
    required this.statusCounts,
    required this.recentOrders,
  });
}
